AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template Sample'
Resources:
  SampleVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.100.0.0/16'
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: 'default'
      Tags:
      - Key: Name
        Value: 'sample-vpc'
    DeletionPolicy: Retain
